TOPDIR ?= ../..
include $(TOPDIR)/.config

$(REMOTEPOWER_SUPPORT)_SRC += services/remotepower/remotepower.c services/remotepower/remotepower_ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
