TOPDIR ?= ../..
include $(TOPDIR)/.config

$(MBI5030_SUPPORT)_SRC += hardware/mbi5030/mbi5030.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
